apiVersion: v2
name: hybrid-node
description: Multi-chain blockchain node deployment — Cardano, ApexFusion, Midnight
type: application
version: 0.3.0
appVersion: "multi-chain"
keywords:
  - cardano
  - apexfusion
  - midnight
  - blockchain
  - stakepool
  - k3s
  - kubernetes
home: https://github.com/gvolcy/Hybrid-Node
sources:
  - https://github.com/gvolcy/Hybrid-Node
maintainers:
  - name: gvolcy
    url: https://github.com/gvolcy
