apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.bp.name }}-topology
  namespace: {{ .Values.namespace }}
data:
  topology.json: |
    {
      "bootstrapPeers": [],
      "localRoots": [
        {
          "accessPoints": [
            {
              "address": "preview2.example.com",
              "port": 6005,
              "description": "preview-relay-1"
            },
            {
              "address": "preview1.example.com",
              "port": 6004,
              "description": "preview-relay-2"
            },
            {
              "address": "preview3.example.com",
              "port": 3001,
              "description": "preview-relay-3"
            }
          ],
          "advertise": false,
          "trustable": true,
          "hotValency": 3,
          "warmValency": 3
        }
      ],
      "publicRoots": [],
      "useLedgerAfterSlot": -1
    }
